import WebsiteFooter from "../components/Footer/page"
import Navigation from "../components/Navigation/page"
import '../globals.css'
import { Toaster } from "@/components/ui/toaster"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className="flex flex-col min-h-screen">
        <Navigation />
        <div className="flex-grow">{children}</div>
        <Toaster />
        <WebsiteFooter />
      </body>
    </html>
  );
}
 